server.port: 7702
spring.application.name: recommendation-service
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: skeleton
  auto-index-creation: true

logging:
  level:
    root: info
    com.unewej: debug
---
spring.config.activate.on-profile: docker
server.port: 8080
