version: '3.7'

services:
  product:
    platform: linux/amd64
    build: microservices/product-service
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  recommendation:
    platform: linux/amd64
    build: microservices/recommendation-service
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    platform: linux/amd64
    build: microservices/review-service
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-composite:
    platform: linux/amd64
    build: microservices/product-composite-service
    container_name: compose
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
