server.port: 7701
spring.application.name: product-service
server.error.include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/skeleton
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: info
    com.unewej: debug
---
spring.config.activate.on-profile: docker
server.port: 8080
