server.port: 7700
spring.application.name: product-composite-service
server.error.include-message: always

app:
  product-service:
    host: localhost
    port: 7701
  recommendation-service:
    host: localhost
    port: 7702
  review-service:
    host: localhost
    port: 7703

logging:
  level:
    root: info
    com.unewej: debug
---
spring.config.activate.on-profile: docker
server.port: 8080

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080
