server.port: 7703
spring.application.name: review-service
server.error.include-message: always

logging:
  level:
    root: info
    com.unewej: debug
---
spring.config.activate.on-profile: docker
server.port: 8080
